### ISSUE TITLE
Fails to create a customization pipeline for Control Tower (CT) Management AWS account 

### ISSUE THREAD

**Issue by libinroy** [aws-ia/terraform-aws-control_tower_account_factory#320] opened 2023-03-03 21:45 UTC
**Terraform Version & Prov:**
1.3.9

**AFT Version:**
1.9.1

**Bug Description**
Adding the CT Management Account to the aft-account-request configs reflects in the aft-request DynamoDB table but does not create the customization pipeline. Looks like the aft-account-request-processor Lambda is failing. See related logs for error.

`module "ct-management" {
  source = "./modules/aft-account-request"

  control_tower_parameters = {
    AccountEmail              = "ct@example.com"
    AccountName               = "CT-Management"
    ManagedOrganizationalUnit = "Root"
    SSOUserEmail              = "ct-user@example.com"
    SSOUserFirstName          = "ct"
    SSOUserLastName           = "user"
  }

  account_tags = {
    "Name" = "CT-Management"
  }

  change_management_parameters = {
    change_requested_by = "CT User"
    change_reason       = "CT Management"
  }

  custom_fields = {
    group = "ct management"
  }

  account_customizations_name = "ct_management"
}`

**Expected behavior**
Customization pipeline should be created for the Control Tower Management AWS account 

**Related Logs**
aft-account-request-processor Lambda Logs: 
```
[ERROR] Exception: No healthy provisioned product found for ct@example.com
Traceback (most recent call last):
  File "/var/task/aft_account_request_processor.py", line 95, in lambda_handler
    update_existing_account(
  File "/opt/python/lib/python3.8/site-packages/aft_common/account_request_framework.py", line 349, in update_existing_account
    raise Exception(
```

**Additional context**
The CT Management Account won't have a Provisioned Product.
Similar issue but different AFT version and error - https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/314

**Comment by Flydiverny** [comment] 2023-03-06 00:27
Would be great if it was possible to import all control tower accounts, like the management account, security account and log archive to be able to apply global and account customisations on those. 
Even the AFT Management Account could be useful to import to able to use global customisation. That is "importable" however it will break the AFT management setup due to a conflict in IAM roles as the provisioning will remove privileges the AFT management account needs.

**Comment by stumins** [comment] 2023-03-06 21:55
Hi @libinroy,

Can you check that both the `AccountEmail` and `AccountName` fields in your request match the actual name & email of your CT Management Account. It is important that **both** fields match the targeted shared account.

---

A longer explanation of what I suspect could be happening here:

The provided error indicates that AFT is incorrectly trying to operate on a CT shared account (in this case, the CT Management account) as if it were a standard member account.

AFT identifies requests for shared accounts using:
1. The shared account IDs provided during the initial deployment of AFT (used to get the name & email of the shared accounts)
2. The account email
3. The account name

When an account request is processed, [AFT compares](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/main/sources/aft-lambda-layer/aft_common/shared_account.py#L40) the account name and account email in the request to the names & emails of the registered shared accounts. If **both** fields match, AFT processes the request as a Shared Account request (using a different code path - e.g. understanding that these special accounts don't have SC Provisioned Products).

In this case, AFT is trying to process the account as a member account, meaning that it didn't find a match on both the name & email of one of the registered shared accounts.

**Comment by stumins** [comment] 2023-03-06 22:00
@Flydiverny 

AFT supports importing any of the CT shared accounts (as well as the AFT Management account) [since v1.4.0](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.4.0). Both the `AccountName` and `AccountEmail` fields in the request need to match as mentioned in my comment above. 

It sounds you might be experiencing an issue when trying to import your AFT Management account into AFT - if so, please file a bug report so that we can investigate.

**Comment by libinroy** [comment] 2023-03-07 03:53
> Hi @libinroy,
> 
> Can you check that both the `AccountEmail` and `AccountName` fields in your request match the actual name & email of your CT Management Account. It is important that **both** fields match the targeted shared account.
> 
> A longer explanation of what I suspect could be happening here:
> 
> The provided error indicates that AFT is incorrectly trying to operate on a CT shared account (in this case, the CT Management account) as if it were a standard member account.
> 
> AFT identifies requests for shared accounts using:
> 
>     1. The shared account IDs provided during the initial deployment of AFT (used to get the name & email of the shared accounts)
> 
>     2. The account email
> 
>     3. The account name
> 
> 
> When an account request is processed, [AFT compares](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/main/sources/aft-lambda-layer/aft_common/shared_account.py#L40) the account name and account email in the request to the names & emails of the registered shared accounts. If **both** fields match, AFT processes the request as a Shared Account request (using a different code path - e.g. understanding that these special accounts don't have SC Provisioned Products).
> 
> In this case, AFT is trying to process the account as a member account, meaning that it didn't find a match on both the name & email of one of the registered shared accounts.

Hi @stumins The passed AccountEmail and AccountName fields are correct. They are for the ct_management_account_id passed during the initial deployment of AFT. 

What would  ManagedOrganizationalUnit value be the CT Management account?

**Comment by stumins** [comment] 2023-11-20 23:32
@libinroy The value depends on where your CT management account is located in your Organization, but is typically "Root". Docs: https://docs.aws.amazon.com/controltower/latest/userguide/aft-update-account.html#aft-update-account-not-provision

I'm going to go ahead and close this ticket as there is no reproducible issue with importing the CT Management account into AFT Management. Please feel free to open a new issue if you experience issues on the latest AFT version.

**Closed** 2023-11-20 23:32 UTC
Labels: bug
