### ISSUE TITLE
AuthorizationErrorException with SNS:Publish

### ISSUE THREAD

**Issue by Menahem1** [aws-ia/terraform-aws-control_tower_account_factory#151] opened 2022-05-11 16:21 UTC
**AFT Version:** 1.3.6

**Bug Description**
Hello,
I encounter the error with the SNS Notification (seems that the permission is missing in the role aft-identify-targets-execution-role with the last update)

[ERROR] AuthorizationErrorException: An error occurred (AuthorizationError) when calling the Publish operation: User: arn:aws:sts:::assumed-role/aft-identify-targets-execution-role/aft-customizations-identify-targets is not authorized to perform: SNS:Publish on resource: arn:aws:sns:::aft-failure-notifications because no identity-based policy allows the SNS:Publish action
Traceback (most recent call last):
  File "/var/task/aft_customizations_identify_targets.py", line 53, in lambda_handler
    notifications.send_lambda_failure_sns_message(
  File "/opt/python/lib/python3.8/site-packages/aft_common/notifications.py", line 48, in send_lambda_failure_sns_message
    send_sns_message(
  File "/opt/python/lib/python3.8/site-packages/aft_common/notifications.py", line 31, in send_sns_message
    response = client.publish(TopicArn=topic, Message=sns_message, Subject=subject)
  File "/opt/python/lib/python3.8/site-packages/botocore/client.py", line 415, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/python/lib/python3.8/site-packages/botocore/client.py", line 745, in _make_api_call
    raise error_class(parsed_response, operation_name)

**To Reproduce**
1. Subscribre to the SNS Topic AFT-Failure
2. Create/simulate a failure on AFT from Lambda _aft-customizations-identify-targets_ (possibly same thing with success)

Thanks

**Comment by snebhu3** [comment] 2022-05-11 18:23
@Menahem1 thank you for reporting this.
I have confirmed that the aft-customizations-identify-targets lambda role is missing the sns:Publish permissions.
I have recorded the bug and we will be looking to it.

**Comment by Menahem1** [comment] 2022-05-13 10:20
I have see the new version (1.3.7) i have now that error

```
[ERROR] ValidationError: 'include' is a required property

Failed validating 'required' in schema:
    {'$id': 'https://example.com/object1626364391.json',
     '$schema': 'http://json-schema.org/draft-07/schema#',
     'definitions': {},
     'properties': {'exclude': {'$id': '#root/exclude',
                                'default': [],
                                'items': {'$id': '#root/exclude/items',
                                          'properties': {'target_value': {'$id': '#root/exclude/items/target_value',
                                                                          'default': [],
                                                                          'items': {'$id': '#root/exclude/items/target_value/items',
                                                                                    'default': '',
                                                                                    'pattern': '^.*$',
                                                                                    'title': 'Items',
                                                                                    'type': ['string',
                                                                                             'object']},
                                                                          'title': 'Target_value',
                                                                          'type': 'array'},
                                                         'type': {'$id': '#root/exclude/items/type',
                                                                  'default': '',
                                                                  'pattern': '^.*$',
                                                                  'title': 'Type',
                                                                  'type': 'string'}},
                                          'required': ['type'],
                                          'title': 'Items',
                                          'type': 'object'},
                                'maxItems': 4,
                                'minItems': 1,
                                'title': 'Exclude',
                                'type': 'array',
                                'uniqueItems': True},
                    'include': {'$id': '#root/include',
                                'default': [],
                                'items': {'$id': '#root/include/items',
                                          'properties': {'type': {'$id': '#root/include/items/type',
                                                                  'default': '',
                                                                  'pattern': '^.*$',
                                                                  'title': 'Type',
                                                                  'type': ['string',
                                                                           'object']}},
                                          'required': ['type'],
                                          'title': 'Items',
                                          'type': 'object'},
                                'maxItems': 4,
                                'minItems': 1,
                                'title': 'Include',
                                'type': 'array',
                                'uniqueItems': True}},
     'required': ['include'],
     'title': 'Root',
     'type': 'object'}

On instance:
    {'Comment': 'Add password policy'}
Traceback (most recent call last):
  File "/var/task/aft_customizations_identify_targets.py", line 30, in lambda_handler
    if not validate_request(payload):
  File "/opt/python/lib/python3.8/site-packages/aft_common/customizations.py", line 147, in validate_request
    validated = jsonschema.validate(payload, schema_object)
  File "/opt/python/lib/python3.8/site-packages/jsonschema/validators.py", line 1013, in validate
    raise error
```

Still for the lambda -> aft-customizations-identify-targets

**Comment by snebhu3** [comment] 2022-05-13 21:56
@Menahem1 this error could indicate that the input payload provided to the aft-invoke-customizations step function was not of the expected format.
Please refer to [Account customizations documentation](https://docs.aws.amazon.com/controltower/latest/userguide/aft-account-customization-options.html) for details about valid input payload schema.

**Comment by balltrev** [comment] 2022-05-23 22:12
Feel free to open a new issue in regards to https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/151#issuecomment-1125888530

I'm going to close this out due to 1.3.7 resolving the permissions issue, thanks!

**Closed by balltrev** 2022-05-23 22:12 UTC
Labels: bug, pending investigation
