### ISSUE TITLE
Expand stages in account-request pipeline with "terraform plan" and approval

### ISSUE THREAD

**Issue by designravenous** [aws-ia/terraform-aws-control_tower_account_factory#302] opened 2023-01-19 10:12 UTC
**Describe the outcome you'd like**
We would like have the option to add "plan" & "approval" stages before the "terrafrom-apply" stage in the module aft-code-repositories (Pipeline ct-aft-account-request). 

We have actually added this scenario in our local module, look in the attached files. 
(aws_codepipeline.codestar_account_request) in codepipeline.tf
(aws_codebuild_project.account_request_plan) in codebuild.tf

And the added buildspec 

No issue, feature request. 
Assure with terraform plan about the resources that will be created.

A clear and concise description of what the problem is.

**Additional context**

[codebuild.zip](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/files/10455654/codebuild.zip)
[codepipeline.zip](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/files/10455657/codepipeline.zip)
[ct-aft-account-request-plan.zip](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/files/10455658/ct-aft-account-request-plan.zip)

**Comment by hanafya** [comment] 2023-01-19 18:23
Hello @designravenous 

This item is a duplicate of this request https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/153. Closing this item as this issue will be tracked in this other ticket.

**Closed** 2023-01-19 18:25 UTC
Labels: duplicate, enhancement
