### ISSUE TITLE
Provide more info in the error notification 

### ISSUE THREAD

**Issue by vaspoz** [aws-ia/terraform-aws-control_tower_account_factory#308] opened 2023-02-01 14:15 UTC
When the event bus `aft-events-from-ct-management` receives an event from Control Tower, it [lambda] processes it. In case of an unrecognized event, it will send a notification in the format:
> An error occurred in the 'aft-invoke-aft-account-provisioning-framework' Lambda function.
For more information, search AWS Request ID 'b527b23d-75a3-47be-a5e5-0a00c67df3a5' in CloudWatch log group '/aws/lambda/aft-invoke-aft-account-provisioning-framework'
Error Message: **Invoked with unrecognized event type**

Since the event type is known (it's a part of event rule definition - ` "eventName": ["SetupLandingZone", "UpdateLandingZone", "RegisterOrganizationalUnit", "DeregisterOrganizationalUnit", "EnableGuardrail", "DisableGuardrail", "CreateManagedAccount", "UpdateManagedAccount"]`), it'd be more useful to include that information in the error [message](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/c86136be8393150aac51f400f42e5c81f2106a20/src/aft_lambda/aft_account_request_framework/aft_invoke_aft_account_provisioning_framework.py#L86):

**Comment by CalvinRodo** [comment] 2023-02-06 18:41
Would it make more sense to not raise an error when a known but not support message type gets passed to the lambda. 

We setup alerting on aft-failure-notifications, and it's a bit noisy when you do things like enable a guardrail and you end up with an alert for every single one of your accounts that are managed by AFT. 

Would it not make more sense to just log that an unsupported control tower event was passed to the lambda? 

I imagine this might just be an oversight, otherwise I'm curious why an unsupported error passed to aft-invoke-aft-account-provisioning-framework should be considered an exception worth raising.

**Comment by vaspoz** [comment] 2023-02-07 15:15
@CalvinRodo it makes sense actually - if it's not an AFT-caused problem, why should we bother?
However, I'd use something in the middle. Because we can say that if there IS an AFT, that's the primary selected tool for account provisioning (you would not want a mix of AFT and CfCT after all). 
Then we should care about **all** of the events related to account management. But then we should significantly reduce the event list to smth like `"eventName": ["CreateManagedAccount", "UpdateManagedAccount"]`. Honestly, I don't understand when there are event for OU and Guardrails =\

**Comment by balltrev** [comment] 2023-02-16 20:15
Hey everyone, we've just released AFT v1.9.0, this release now only listens for the "CreateManagedAccount" and "UpdateManagedAccount" events. This will reduce the noise caused by AFT attempting to process unsupported events.

**Comment by stumins** [comment] 2023-03-02 01:18
Resolved in 1.9.0

**Closed by stumins** 2023-03-02 01:18 UTC
Labels: enhancement
