### ISSUE TITLE
Service call quotas sometimes exceeded

### ISSUE THREAD

**Issue by PeterBengtson** [aws-ia/terraform-aws-control_tower_account_factory#74] opened 2022-02-13 12:20 UTC
The state machines sometimes fail due to contention of resources, i.e. too many simultaneous API calls, for instance when trying to determine how many state machines are already running. The retries should definitely be increased in number, not just there, but across the board. This particular one has occurred 12 times out of 44 total runs.

**Comment by PeterBengtson** [comment] 2022-02-13 12:23
{"errorMessage":"An error occurred (TooManyRequestsException) when calling the DescribeOrganizationalUnit operation (reached max retries: 4): AWS Organizations can't complete your request because another request is already in progress. Try again later.","errorType":"TooManyRequestsException","stackTrace":["  File \"/var/task/aft_account_provisioning_framework_get_account_info.py\", line 27, in lambda_handler\n    return get_account_info(payload, session, ct_management_session)\n","  File \"/opt/python/lib/python3.8/site-packages/aft_common/account_provisioning_framework.py\", line 163, in get_account_info\n    account_id = utils.get_account_id_from_email(ct_management_session, email)\n","  File \"/opt/python/lib/python3.8/site-packages/aft_common/aft_utils.py\", line 170, in get_account_id_from_email\n    accounts = list_accounts(ct_management_session)\n","  File \"/opt/python/lib/python3.8/site-packages/aft_common/aft_utils.py\", line 189, in list_accounts\n    account_info.append(get_account_info(ct_management_session, a[\"Id\"]))\n","  File \"/opt/python/lib/python3.8/site-packages/aft_common/aft_utils.py\", line 208, in get_account_info\n    org_details = client.describe_organizational_unit(\n","  File \"/opt/python/lib/python3.8/site-packages/botocore/client.py\", line 386, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n","  File \"/opt/python/lib/python3.8/site-packages/botocore/client.py\", line 705, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"]}

**Comment by snebhu3** [comment] 2022-02-14 19:16
@PeterBengtson thank you for the good call out and to provide the context. We have created a backlog to increase retries to service calls.

**Comment by stefanolczak** [comment] 2022-04-26 10:46
I just encountered the issue during the test of invoking customizations on multiple accounts. Only 5 ( out of 10+ ) of them were successfully triggered to invoke customization. The issue is a big blocker for us as one of the main reasons of using AFT was a possibility to deploy terraform deployments to multiple accounts at once.

**Comment by stefanolczak** [comment] 2022-04-26 11:28
Actually it appears that customizations are being invoked on next accounts despite the errors mentioned above. According to the [documentation](https://docs.aws.amazon.com/controltower/latest/userguide/aft-account-customization-options.html#aft-re-invoke-customizations) there is a limit of 5 accounts that can be processed at the same time and the others are queued. Anyway the throttling errors are confusing.

**Comment by stumins** [comment] 2022-05-09 19:02
This issue has been resolved in the latest release, [1.3.6](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.3.6). 

I'm going to close this issue now, but please cut a new issue if you encounter any additional API throttling (`TooManyRequestsException` errors).

**Closed by stumins** 2022-05-09 19:02 UTC
Labels: bug, enhancement
