### ISSUE TITLE
Provide single repo configuration

### ISSUE THREAD

**Issue by lnozot-vt** [aws-ia/terraform-aws-control_tower_account_factory#362] opened 2023-06-22 17:06 UTC
**Describe the outcome you'd like**

Would like to see the ability to use a single repo with paths to the various folders for the functions such as aft-account-request, aft-global-customizations, etc. instead of requiring a repo for each function.  This would enable us to consolidate instead of proliferating the use of more repos.

**Is your feature request related to a problem you are currently experiencing? If so, please describe.**

A clear and concise description of what the problem is.

**Additional context**

**Comment by stumins** [comment] 2023-06-26 23:47
Hi @lnozot-vt, thanks for submitting this enhancement request. I believe this a duplicate of https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/186, so I'm closing in favor of the older issue. Please track status under #186 - if you believe there is additional context not captured in 186, please add it in the comments or let me know in this issue. Thanks!

**Closed** 2023-06-26 23:47 UTC
Labels: duplicate, enhancement
