### ISSUE TITLE
module.aft-account-request-framework.aws_backup_selection.aft_controltower_backup_selection causes drift

### ISSUE THREAD

**Issue by jeremyciak** [aws-ia/terraform-aws-control_tower_account_factory#37] opened 2022-01-21 02:56 UTC
It looks like the `aws_backup_selection` not having a blank `condition` and empty `not_resources` properties defined causes drift. I believe that changing the order would fix this.

```
Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # module.aft.module.aft_account_request_framework.aws_backup_selection.aft_controltower_backup_selection has changed
  ~ resource "aws_backup_selection" "aft_controltower_backup_selection" {
        id            = "abcd1234-ab12-ab12-ab12-abcdef123456"
        name          = "aft-controltower-backup-selection"
      + not_resources = []
        # (3 unchanged attributes hidden)

      + condition {
        }
    }


Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these changes.   

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 


Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place
-/+ destroy and then create replacement

Terraform will perform the following actions:
# module.aft.module.aft_account_request_framework.aws_backup_selection.aft_controltower_backup_selection must be replaced
-/+ resource "aws_backup_selection" "aft_controltower_backup_selection" {
      ~ id            = "abcd1234-ab12-ab12-ab12-abcdef123456" -> (known after apply)
        name          = "aft-controltower-backup-selection"
      - not_resources = [] -> null
        # (3 unchanged attributes hidden)

      - condition { # forces replacement
        }
    }
```

**Comment by mathewmoon** [comment] 2022-01-21 03:43
@jeremyciak possible duplicate of https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/35

**Comment by jeremyciak** [comment] 2022-01-21 04:37
@mathewmoon good call. I created PR #38 which I will link to #35 as well.

**Comment by balltrev** [comment] 2022-01-21 22:12
This looks to be related to https://github.com/hashicorp/terraform-provider-aws/issues/22595

**Comment by balltrev** [comment] 2022-01-21 22:55
I do see the workaround you've listed in the issue I linked above. We'll see if we can't reproduce and test the workaround.

**Comment by stumins** [comment] 2022-01-25 23:13
Hi, release [1.1.2](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.1.2) should resolve this issue. Please feel free to re-open if you're still experiencing any issues.

**Closed by stumins** 2022-01-25 23:13 UTC
