### ISSUE TITLE
Account customizations are mandatory, not optional

### ISSUE THREAD

**Issue by KevinDHunter** [aws-ia/terraform-aws-control_tower_account_factory#168] opened 2022-05-25 16:58 UTC
**Terraform Version & Prov:**

**AFT Version:** 1.3.7

**Terraform Version & Provider Versions**

`terraform version`
```
1.1.9 and 0.15.5 - failed either way
```

`terraform providers`
```
hashicorp/aws v4.15.1
```

**Bug Description**
Although the documentation describes account customizations as optional (using words like "may"), if you do not provide an account customization name, the insertion into the `aft-request` DynamoDB table fails, meaning that the account request fails.

**To Reproduce**
1. Create an account request that is either missing the account_customizations_name parameter, or where the parameter is `null`.
2. Merge the request into the appropriate branch in the account requests repository.
3. The account request fails due to an error in the  `ct-aft-account-request` CodeBuild project 

**Expected behavior**
Expected the request to succeed, and the account customization step to just be skipped.

**Related Logs**
The significant log output from the `ct-aft-account-request` CodeBuild project is below.  The issue appears to be that it is attempting to insert a `null` value for `account_customizations_name`, but that the `account_customizations_name` is of type "string" rather  than "null" (or being omitted.)
```
Terraform will perform the following actions:

  # module.playground-inspection.aws_dynamodb_table_item.account-request will be created
  + resource "aws_dynamodb_table_item" "account-request" {
      + hash_key   = "id"
      + id         = (known after apply)
      + item       = jsonencode(
            {
              + account_customizations_name  = {
                  + S = null
                }
              + account_tags                 = {
                  + S = jsonencode(
                        {
                          + Infra:AccountType          = "infrastructure"
                          + Infra:App                  = "infrastructure"
                          + Infra:Environment          = "infrastructure"
                          + Infra:FullName             = "peeriq-park-playground-inspection"
                          + Infra:Name                 = "Playground Inspection"
                          + Infra:Organization         = "park"
                          + Infra:OrganizationId       = "o-beb54wk01o"
                          + Infra:OrganizationalUnit   = "Inspection"
                          + Infra:OrganizationalUnitId = "ou-c7za-dqf571ft"
                        }
                    )
                }
              + change_management_parameters = {
                  + M = {
                      + change_reason       = {
                          + S = "Initial organization setup"
                        }
                      + change_requested_by = {
                          + S = "PeerIQ AWS Orgs Infrastructure team"
                        }
                    }
                }
              + control_tower_parameters     = {
                  + M = {
                      + AccountEmail              = {
                          + S = "AWSRoot+peeriq-park-playground-inspection@peeriq.com"
                        }
                      + AccountName               = {
                          + S = "Playground Inspection"
                        }
                      + ManagedOrganizationalUnit = {
                          + S = "Inspection (ou-c7za-dqf571ft)"
                        }
                      + SSOUserEmail              = {
                          + S = "AWSRoot+Fake-SSO-User@peeriq.com"
                        }
                      + SSOUserFirstName          = {
                          + S = "Fake"
                        }
                      + SSOUserLastName           = {
                          + S = "User"
                        }
                    }
                }
              + custom_fields                = {
                  + S = jsonencode({})
                }
              + id                           = {
                  + S = "AWSRoot+peeriq-park-playground-inspection@peeriq.com"
                }
            }
        )
      + table_name = "aft-request"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
module.playground-inspection.aws_dynamodb_table_item.account-request: Creating...
╷
│ Error: ValidationException: Supplied AttributeValue is empty, must contain exactly one of the supported datatypes
│   status code: 400, request id: QJJJ6THDNT5PH2GRIA8JRBTUTJVV4KQNSO5AEMVJF66Q9ASUAAJG
│ 
│   with module.playground-inspection.aws_dynamodb_table_item.account-request,
│   on modules/aft-account-request/ddb.tf line 1, in resource "aws_dynamodb_table_item" "account-request":
│    1: resource "aws_dynamodb_table_item" "account-request" {
│ 
```

**Comment by balltrev** [comment] 2022-05-27 18:27
Hey @KevinDHunter, I think this is actually a feature request of AFT as it was designed as a way to extend/customize your landing zone via Terraform.

I've gone ahead and created a backlog to add this optionality to AFT

**Comment by KevinDHunter** [comment] 2022-05-27 18:34
I understand the purpose.  The point is that we have some accounts where the logic in the global customization is sufficient, so we don't need additional account-specific customization as part of AFT.  (Anything else going into the account is going to be put in by the developers after the "account vending team" has gotten the baseline account set up.)

The Control Tower user's guides uses the following language:
```
Account customizations (optional)

To customize an individual account, or a set of accounts, differently than other AFT provisioned accounts,
you can leverage the account customizations portion of the AFT pipeline to implement account-specific
configurations. For example, only a certain account may require access to an internet gateway.
```

The point is that account customizations are NOT optional, as stated - you MUST specify an account customization or things don't work.  So, at minimum, you have to have a "no-op" customization.

In addition, if an account customization is not optional, then that field in the account request module should not have a default.

Thus, I consider this a bug, not an enhancement request, because it doesn't behave as documented.

**Comment by stumins** [comment] 2022-07-27 16:32
Hi @KevinDHunter, 

We were not able to reproduce this issue. We were able to both create a new account without specifying the `account_customizations_name` field as well as remove the `account_customizations_name` field from an existing account and run the customization pipeline without issue.

Are you able to provide more specific steps to reproduce? 

It would be helpful if you could provide the `{account_request}.tf` file that caused this issue for you (please remember to remove any personal or sensitive information).

**Comment by KevinDHunter** [comment] 2022-07-27 18:25
While this may be the case now, it was not the case when the bug report was filed.

The company for which I work has abandoned the use of AFT, so I'm unable to give you an example.

Based on what you're saying, it appears that the issue has been corrected, so you can probably just close this issue.

**Comment by stumins** [comment] 2022-07-27 20:55
It's unclear to me what happened here, as the customization field has had a default value of an empty string [since at least 1.0.0](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/32c9bb5139a575f52e6d4d9b785b623eea5cdd21/sources/aft-customizations-repos/aft-account-request/terraform/modules/aft-account-request/variables.tf#L44).

However, I understand this issue is no longer impacting you, so I'll go ahead and close it. Our apologies for the rough experience and we hope you consider using AFT again in the future.

**Closed by stumins** 2022-07-27 20:55 UTC
Labels: bug, unable to reproduce
