### ISSUE TITLE
Apply custom tags to ALL resources created by module

### ISSUE THREAD

**Issue by davcen** [aws-ia/terraform-aws-control_tower_account_factory#313] opened 2023-02-24 16:00 UTC
**Describe the outcome you'd like**

I would like to apply a map of custom tags to ALL AWS resources (that support tagging) created by this module.

**Is your feature request related to a problem you are currently experiencing? If so, please describe.**

My current problem is related to a project that i'm following for a customer, involved in [AWS Migration Acceleration Program](https://aws.amazon.com/migration-acceleration-program/): this program requires to tag all the elegible resources that generates costs in order to cover a part of them with credit from AWS itself.

I'm using this module to handle the Accont Factory for the landing zone of the customer infrastructure, and the related resources (VPC endpoints in first places) generates a quite amounts of costs, but i can't tag them as i wish, because the module define only a static value `managed_by = "AFT"` using "default_tags" feature of AWS provider

**Additional context**

I suggest to add an input variable like `all_tags` or `tags`, defined like this
```
variable "tags" {
  description = "A map of tags to add to all resources"
  type        = map(string)
  default     = {}
}
```
and use in the main providers configuration, for example
```
provider "aws" {
  alias  = "ct_management"
  region = var.ct_home_region
  # The default profile or environment variables should authenticate to the Control Tower Management Account as Administrator
  default_tags {
    tags = merge(
      {
        managed_by = "AFT"
      },
      var.tags
    )
  }
}
```

**Comment by balltrev** [comment] 2023-02-24 21:25
Thanks @davcen for the request, I believe it's a duplicate of https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/23. I'll go ahead and add this as well to our existing backlog with the team.

**Closed by balltrev** 2023-02-24 21:25 UTC
Labels: duplicate, enhancement
