### ISSUE TITLE
V1.4.1 fails to update SSM parameters

### ISSUE THREAD

**Issue by paulpog-checkit** [aws-ia/terraform-aws-control_tower_account_factory#182] opened 2022-06-02 15:40 UTC
We just released AFT [v1.4.1](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.4.1) which resolves the `Warning: Provider aws is undefined` warnings.

_Originally posted by @snebhu3 in https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/163#issuecomment-1142660847_

I have just updated and tried to apply V1.4.1 and it fails when trying to change the following two ssm parameters:
1. /aft/config/aft/version
2. /aft/config/aft-pipeline-code-source/repo-git-ref

with the following error:
ParameterAlreadyExists: The parameter already exists. To overwrite this value, set the overwrite option in the request to true.

**Comment by paulpog-checkit** [comment] 2022-06-02 15:41
Here is the full copy of the console output:
`Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.aft.module.aft_ssm_parameters.aws_ssm_parameter.aft_framework_repo_git_ref will be updated in-place
  ~ resource "aws_ssm_parameter" "aft_framework_repo_git_ref" {
        id        = "/aft/config/aft-pipeline-code-source/repo-git-ref"
        name      = "/aft/config/aft-pipeline-code-source/repo-git-ref"
        tags      = {}
      ~ value     = (sensitive value)
      ~ version   = 2 -> (known after apply)
        # (6 unchanged attributes hidden)
    }

  # module.aft.module.aft_ssm_parameters.aws_ssm_parameter.aft_version will be updated in-place
  ~ resource "aws_ssm_parameter" "aft_version" {
        id        = "/aft/config/aft/version"
        name      = "/aft/config/aft/version"
        tags      = {}
      ~ value     = (sensitive value)
      ~ version   = 2 -> (known after apply)
        # (6 unchanged attributes hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Saved the plan to: plan.txt

To perform exactly these actions, run the following command to apply:
    terraform apply "plan.txt"
(venv) PPogonoski@Administrators-MacBook-Pro AWS-Control-Tower-AFT % terraform apply "plan.txt"  
module.aft.module.aft_ssm_parameters.aws_ssm_parameter.aft_framework_repo_git_ref: Modifying... [id=/aft/config/aft-pipeline-code-source/repo-git-ref]
module.aft.module.aft_ssm_parameters.aws_ssm_parameter.aft_version: Modifying... [id=/aft/config/aft/version]
╷
│ Error: error updating SSM parameter (/aft/config/aft/version): ParameterAlreadyExists: The parameter already exists. To overwrite this value, set the overwrite option in the request to true.
│ 
│   with module.aft.module.aft_ssm_parameters.aws_ssm_parameter.aft_version,
│   on .terraform/modules/aft/modules/aft-ssm-parameters/ssm.tf line 178, in resource "aws_ssm_parameter" "aft_version":
│  178: resource "aws_ssm_parameter" "aft_version" {
│ 
╵
╷
│ Error: error updating SSM parameter (/aft/config/aft-pipeline-code-source/repo-git-ref): ParameterAlreadyExists: The parameter already exists. To overwrite this value, set the overwrite option in the request to true.
│ 
│   with module.aft.module.aft_ssm_parameters.aws_ssm_parameter.aft_framework_repo_git_ref,
│   on .terraform/modules/aft/modules/aft-ssm-parameters/ssm.tf line 268, in resource "aws_ssm_parameter" "aft_framework_repo_git_ref":
│  268: resource "aws_ssm_parameter" "aft_framework_repo_git_ref" {
│ 
╵
`

**Comment by snebhu3** [comment] 2022-06-03 17:16
@paulpog-checkit the error suggests there could be an issue with the Terraform state file in the environment. 
Can you confirm that the state file is in the expected state?

**Comment by paulpog-checkit** [comment] 2022-06-03 20:34
@snebhu3  if there was an issue with the state file then why, for both resources, the plan says that they will be "updated in-place"?
The issue is that the SSM resources are coded with the false logic that they will only ever be created and not changed. 
This is a bug and, as the error message suggests, they need to have "set the overwrite option in the request to true".
I got passed this issue with v1.40 b=y cloning the repo and setting these values, on all the ssm resources, but I think the base code needs addressing.

**Comment by balltrev** [comment] 2022-06-03 21:58
@paulpog-checkit, looking at the documentation for the [overwrite argument on the ssm_parameter resource](https://registry.terraform.io/providers/hashicorp%20%20/aws/latest/docs/resources/ssm_parameter#overwrite), I see it mentions overwrite will default to `false` if Terraform did not provision the parameter.

This makes me think that for some reason the state file in your environment was unaware that it had provisioned these SSM Parameters, and threw the error you saw above.

According to the docs for overwrite, assuming now that Terraform "owns" the SSM Parameters in question due to you specifying overwrite as true, your state file issues may have been resolved, allowing you to revert back to an un-forked version of AFT.

**Comment by paulpog-checkit** [comment] 2022-06-04 09:55
@balltrev Thanks for taking the time to explain this.
Due to the fact that I had to originally set up AFT in a cloudshell in the AWS Control Tower management account, and the saved state file became corrupted, I had to import a great deal of the already created AFT for the 1.4 upgrade, but I did explicitly set the  overwrite to true for the SSM parameters.
I was assuming that once defined int he state file (either via import or its normal workings) terraform knows it created it. Is that not true? Are imported resources treated differently to created ones?

**Comment by paulpog-checkit** [comment] 2022-06-04 10:29
@balltrev  I've just tested your theory about explicitly setting the overwrite flag (with a cloned version of AFT) to get the apply to work, then reverting back to the "official" github module, and the results are not good.
I when and changed all 81 ssm resources and the apply worked, specifying that it had to change all resources to add the overwrite flag.
Then I pointed the module bag to the git hub instance and ran the plan and it showed the all 81 of the resources needed to change to remove the overwrite.
Then I ran the apply, and all 81 of the resources failed with the same error " The parameter already exists. To overwrite this value, set the overwrite option in the request to true."

This is terraform doing it every time, so I cannot see how it is Terraform thinking it doesn't own the resource.

I also find it interesting that no one else is having this issue.

**Comment by paulpog-checkit** [comment] 2022-06-04 11:49
@balltrev I done some more testing.
Given that the documentation hints at ownership causing the issue I did the following:
1. removed the overwrite flag from all 61 (my original figure of 81 was wrong) resources in my cloned code
2. ran plan and apply
3. the result was the same as using the GitHub module ... all 61 failed with the " The parameter already exists. To overwrite this value, set the overwrite option in the request to true." error.

This is strange because the overwrite=true is set on the ssm parameters, so it should allow it being removed, should it not?

This also indicates that it has nothing to do with how the resource was defined to the state file, but rather how the provider treats the resource if the flag is not set, or to be removed. Which, I would suggest, means that this flag needs to be set to true otherwise upgrades won't work.

This brings me back to the question above.... why is no-one else experiencing this?

**Comment by stumins** [comment] 2022-06-06 19:52
Hi @paulpog-checkit,

I'm sorry you're experiencing these challenges while using AFT. We test overwriting existing SSM parameters (created by AFT) as part of our build pipelines and have not been able to replicate this issue.

I suspect there is a deeper root cause present here. Unfortunately, we are unable to provide detailed per-user support through this channel. 

Please open a ticket with AWS Premium Support and they can assist with resolving this issue. You may also consider reaching out to Hashicorp support for questions about resource importing or the mechanics of the state file.

**Closed** 2022-06-13 16:30 UTC
Labels: bug, unable to reproduce
