### ISSUE TITLE
Enable creating accounts without a VPC

### ISSUE THREAD

**Issue by mbuotidem** [aws-ia/terraform-aws-control_tower_account_factory#152] opened 2022-05-12 04:56 UTC
**Provide a flag that prevents AFT from creating any VPC's beyond those required for Codebuild**

Alternatively, some way to tell AFT to use IPAM to create its VPC would be nice. 

**Is your feature request related to a problem you are currently experiencing? If so, please describe.**

I would like to use Amazon's IP Address Manager [IPAM](https://docs.aws.amazon.com/vpc/latest/ipam/what-it-is-ipam.html) to manage VPC's in my Control Tower managed accounts. AFT's current behavior is to create VPC's with the same default CIDR ranges. Thus, to setup IPAM, it seems like I would have to manually go and cleanup all the VPC's that AFT creates, defeating to some extent, the point of using automation. 

**Additional context**

There seems to be a [way](https://docs.aws.amazon.com/controltower/latest/userguide/configure-without-vpc.html) to do this manually through the UI, so it would be nice to have the option on AFT.

**Comment by snebhu3** [comment] 2022-05-12 20:44
@mbuotidem Thank you for the feature request and the details.
I have created an internal backlog to track this request.

**Comment by owenfarrell** [comment] 2022-05-14 21:39
@mbuotidem - is this a duplicate of #142, or are you asking for something different?

**Comment by mbuotidem** [comment] 2022-05-17 01:40
@owenfarrell It was unclear to me from the documentation if AFT will create VPC's in all my vended accounts even if I had asked Control Tower not to using the steps at  [configure Control Tower without a VPC](https://docs.aws.amazon.com/controltower/latest/userguide/configure-without-vpc.html).  But I guess the flag in the issue you linked should take care of this for me. I'll try it!

**Comment by stumins** [comment] 2023-10-23 19:03
Hi @mbuotidem, apologies for the late follow up here.

If you follow the process to configure Control Tower to create accounts without VPCs, then accounts created by AFT will also not have CT-created VPCs in them. As such, I believe the "no VPC" ask of this request has already been met.

I've copied the IPAM integration feature request into its own ticket. Please use https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/401 for IPAM tracking purposes.

**Closed by stumins** 2023-10-23 19:03 UTC
Labels: enhancement
