### ISSUE TITLE
 (AccessDeniedException) when calling the GetParametersByPath in `aft_account_provisioning_framework_account_metadata_ssm`

### ISSUE THREAD

**Issue by michaelw** [aws-ia/terraform-aws-control_tower_account_factory#180] opened 2022-06-02 03:40 UTC
**Terraform Version & Prov:**

**AFT Version:**
1.4.1

**Terraform Version & Provider Versions**
Please provide the outputs of `terraform version` and `terraform providers` from within your AFT environment

`terraform version`
```
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v4.16.0
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/random v3.2.0
+ provider registry.terraform.io/hashicorp/time v0.7.2
```

`terraform providers`
```
Providers required by configuration:
.
├── provider[registry.terraform.io/hashicorp/aws] ~> 4.0
├── module.enforce_mfa
│   └── provider[registry.terraform.io/hashicorp/aws] >= 3.38.0
└── module.aft
    ├── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0, < 5.0.0
    ├── provider[registry.terraform.io/hashicorp/local]
    ├── module.packaging
        └── provider[registry.terraform.io/hashicorp/archive]
    ├── module.aft_feature_options
        └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    ├── module.aft_account_provisioning_framework
        └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    ├── module.aft_code_repositories
        ├── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
        └── provider[registry.terraform.io/hashicorp/local]
    ├── module.aft_customizations
        ├── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
        └── provider[registry.terraform.io/hashicorp/local]
    ├── module.aft_iam_roles
        ├── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
        ├── module.audit_service_role
            └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
        ├── module.ct_management_exec_role
            └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
        ├── module.ct_management_service_role
            └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
        ├── module.log_archive_exec_role
            └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
        ├── module.log_archive_service_role
            └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
        ├── module.aft_exec_role
            └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
        ├── module.aft_service_role
            └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
        └── module.audit_exec_role
            └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    ├── module.aft_ssm_parameters
        └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    ├── module.aft_account_request_framework
        ├── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
        └── provider[registry.terraform.io/hashicorp/time]
    ├── module.aft_backend
        └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    └── module.aft_lambda_layer
        ├── provider[registry.terraform.io/hashicorp/random]
        ├── provider[registry.terraform.io/hashicorp/local]
        └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0

Providers required by state:

    provider[registry.terraform.io/hashicorp/aws]

    provider[registry.terraform.io/hashicorp/archive]

    provider[registry.terraform.io/hashicorp/local]

    provider[registry.terraform.io/hashicorp/random]

    provider[registry.terraform.io/hashicorp/time]

```

**Bug Description**

**To Reproduce**
0. After upgrading AFT from 1.4.0 to 1.4.1
1. Create new account (via commit to aft-account-request repo)
2. Observe that pipelines succeed, but account specific pipelines are not created
3. Go to Step Function aft-account-provisioning-framework, observe failure in aft_account_provisioning_framework_account_metadata_ssm. (see below for logs)
4. Reverting to 1.4.0 fixes the permission issue.

**Expected behavior**
account specific customization pipelines are created

**Related Logs**
Failure logs of Step Function:
```
{
  "resourceType": "lambda",
  "resource": "invoke",
  "error": "ClientError",
  "cause": "{\"errorMessage\":\"An error occurred (AccessDeniedException) when calling the GetParametersByPath operation: User: arn:aws:sts::033629590623:assumed-role/AWSAFTService/AWSAFT-Session is not authorized to perform: ssm:GetParametersByPath on resource: arn:aws:ssm:us-east-2:033629590623:parameter/aft/account-request/custom-fields/ because no identity-based policy allows the ssm:GetParametersByPath action\",\"errorType\":\"ClientError\",\"stackTrace\":[\"  File \\\"/var/task/aft_account_provisioning_framework_account_metadata_ssm.py\\\", line 59, in lambda_handler\\n    params = get_ssm_parameters_names_by_path(\\n\",\"  File \\\"/opt/python/lib/python3.8/site-packages/aft_common/account_provisioning_framework.py\\\", line 204, in get_ssm_parameters_names_by_path\\n    response = client.get_parameters_by_path(Path=path, Recursive=True)\\n\",\"  File \\\"/opt/python/lib/python3.8/site-packages/botocore/client.py\\\", line 415, in _api_call\\n    return self._make_api_call(operation_name, kwargs)\\n\",\"  File \\\"/opt/python/lib/python3.8/site-packages/botocore/client.py\\\", line 745, in _make_api_call\\n    raise error_class(parsed_response, operation_name)\\n\"]}"
}
```

**Comment by Menahem1** [comment] 2022-06-02 08:20
Hello,
See https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/177

**Comment by stumins** [comment] 2022-06-02 17:30
Hi @michaelw, thanks for reporting this issue. I believe this is a duplicate of the pinned issue #177 - please track resolution via https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/177.

If this is not correct, please feel free to re-open this issue.

**Closed by stumins** 2022-06-02 17:30 UTC
Labels: bug, pending investigation
