### ISSUE TITLE
Make `ct-aft-account-provisioning-customizations` Terraform workspace name dynamic in AFT solution

### ISSUE THREAD

**Issue by andylim0221** [aws-ia/terraform-aws-control_tower_account_factory#278] opened 2022-11-14 14:20 UTC
**Describe the outcome you'd like**

We'd like to request to make `ct-aft-account-provisioning-customizations` Terraform workspace name as dynamic in AFT solution. 

**Is your feature request related to a problem you are currently experiencing? If so, please describe.**

We have two AWS Organizations, one for production environment while the other is for development environment. When we installed and configured AFT solution in development environment, we had this workspace `ct-aft-account-provisioning-customizations` automatically provisioned as it's part of the AFT solution. Then, we moved on to promoting AFT in production environment. However, we face this issue where we want to make customizations for an account request, the `ct-aft-account-provisioning-customizations` failed as it has conflict with the step function and IAM role resources created in development environment, which was a roadblock for us to move forward on promoting AFT to production environment. 

What would I suggest is to make the workspace name `ct-aft-account-provisioning-customizations` dynamic so that this can fit into different AWS Organizations under the same Terraform Cloud Organization.

Reference code line: https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/0f2caea57e37a1a58dc305e2f342e9c28aeb9c41/modules/aft-code-repositories/buildspecs/ct-aft-account-provisioning-customizations.yml#L67

**Comment by hanafya** [comment] 2022-11-17 17:39
Hello!

This is a duplicate of this following issue: https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/50

However, i have added your request to existing backlog item!

**Closed by hanafya** 2022-11-17 17:39 UTC
Labels: enhancement
